/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/zvVA8GY90vo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"

export function vote() {
  return (
    (<div
      className="flex flex-col items-center justify-center min-h-screen bg-gray-100">
      <div className="w-full max-w-sm p-6 bg-white rounded-lg shadow-lg">
        <div className="flex items-center justify-center">
          <img
            src="/placeholder.svg"
            alt="Logo"
            className="mr-4"
            width="100"
            height="100"
            style={{ aspectRatio: "100/100", objectFit: "cover" }} />
          <img
            src="/placeholder.svg"
            alt="Logo"
            width="100"
            height="100"
            style={{ aspectRatio: "100/100", objectFit: "cover" }} />
        </div>
        <div className="p-6 mt-4 bg-white rounded-lg shadow-lg">
          <div className="flex flex-col items-center justify-center">
            <Avatar className="w-24 h-24 mb-4">
              <AvatarImage src="/placeholder-user.jpg" alt="Candidate" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
            <h2 className="text-lg font-semibold">Mukti Upadhyay</h2>
            <p className="text-center text-muted-foreground">
              Please vote me for something I have done. Please vote me.
            </p>
          </div>
          <div className="mt-6 text-center">
            <p>Please cast your vote on a scale of 1 to 10, with 1 being the worst and 10 being the best.</p>
            <div className="grid grid-cols-3 gap-4 mt-4">
              {[1, 2, 3, 4, 5, 6, 7, 8, 9].map((number) => (
                <Button key={number} variant="outline" className="w-full h-12">
                  {number}
                </Button>
              ))}
              <Button variant="default" className="w-full h-12">
                10
              </Button>
            </div>
          </div>
          <div className="flex justify-between mt-6">
            <Button variant="secondary" className="w-1/2 mr-2">
              Previous
            </Button>
            <Button variant="default" className="w-1/2 ml-2">
              Next
            </Button>
          </div>
        </div>
        <Button variant="secondary" className="w-full mt-4">
          Submit Vote
        </Button>
      </div>
    </div>)
  );
}
